### ISSUE TITLE
Additional database elements

### ISSUE THREAD

**Issue by danieljaffe** [uclaacm/discord-verification-bot#2]
#### Required Fields:
- [x] `UCLA Affiliation` given the choices of `student`, `alumni`, and `other`
- [x] `Name`
- [x] `Email` - must end in `ucla.edu`
> !iam Student Daniel Jaffe daniel.jaffe@ucla.edu

 
#### Optional Fields:
- [x] `Major`
- [x] `Graduation Year`
- [x] `Transfer Student` - toggleable flag
- [x] `Pronouns`
> !major Computer Science
> !year 2022
> !transfer
> !pronouns he/him

**Comment by entrohpy** [comment]
Complete. Will close after you verify.

**Comment by danieljaffe** [comment]
Awesome-- great job! Thanks for all your hard work!
