### ISSUE TITLE
Updated accepted emails

### ISSUE THREAD

**Issue by danieljaffe** [uclaacm/discord-verification-bot#4]
We need to be able to accept any email ending in `.ucla.edu`. If the space between `@` and `.ucla.edu` is blank, we must insert a `g` so that we are using the most responsive servers

**Comment by entrohpy** [comment]
I believe some people have `<username>@ucla.edu` aliases that do not map to `<username>@ucla.edu`. Looking into this.

**Comment by danieljaffe** [comment]
### From our verbal discussion:

We will implement the solution both ways and defer to PVP in the morning regarding definitive preference, but this is the alternative to appending the `g`.
- Welcome message will encourage them to use g.ucla.edu instead of ucla.edu 
> No modification of what they entered is required for this method.

**Comment by danieljaffe** [comment]
Looks good!
